platform :ios, '7.0'

pod 'DesignKit', :path => '../DesignKit.podspec'

pod 'Haystack', :git => 'https://github.com/legoless/Haystack.git'
pod 'NUI'
pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git'
pod 'pop'